url: https://www.mapbox.com
api: https://www.mapbox.com/core
tileApi: https://api.tiles.mapbox.com
source: docs
permalink: /:categories/:title
baseurl: /mapbox-android-sdk
highlighter: pygments
version: 0.5.1
snapshot: 0.6.0-SNAPSHOT
defaultid: 'examples.map-i86nkdio'
rdiscount:
  extensions: [smart]
